services:
  rikudou.clock.default:
    class: Rikudou\Clock\Clock

  rikudou.dynamo_cache.encoder.serialize:
    class: Rikudou\DynamoDbCache\Encoder\SerializeItemEncoder

  rikudou.dynamo_cache.encoder.json:
    class: Rikudou\DynamoDbCache\Encoder\JsonItemEncoder
    arguments:
      - '%rikudou.dynamo_cache.json_encoder.encode_flags%'
      - '%rikudou.dynamo_cache.json_encoder.decode_flags%'
      - '%rikudou.dynamo_cache.json_encoder.depth%'

  rikudou.dynamo_cache.encoder.default: '@rikudou.dynamo_cache.encoder.serialize' # redefined in extension

  rikudou.dynamo_cache.cache: # arguments defined in extension
    class: Rikudou\DynamoDbCache\DynamoDbCache
    arguments:
      $clock: '@rikudou.clock.default'
      $converter: '@rikudou.dynamo_cache.converter_registry'
      $encoder: '@rikudou.dynamo_cache.encoder.default'

  rikudou.dynamo_cache.adapter:
    class: Rikudou\DynamoDbCacheBundle\Cache\DynamoDbCacheAdapter
    arguments:
      - '@rikudou.dynamo_cache.cache'
      - '@rikudou.dynamo_cache.converter.cache_item'

  rikudou.dynamo_cache.converter.cache_item:
    class: Rikudou\DynamoDbCacheBundle\Converter\SymfonyCacheItemConverter
    arguments:
      - '@rikudou.clock.default'
      - '@rikudou.dynamo_cache.encoder.default'
    tags:
      - rikudou.dynamo_cache.converter

  rikudou.dynamo_cache.converter_registry:
    class: Rikudou\DynamoDbCache\Converter\CacheItemConverterRegistry

  rikudou.dynamo_cache.session:
    class: Rikudou\DynamoDbCacheBundle\Session\DynamoDbSessionHandler
    arguments:
      - '@rikudou.dynamo_cache.adapter'
